# Generated by Django 4.0.2 on 2022-02-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactergroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='charactergroup',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for this group.', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, help_text='Global slug of the character, will be auto generated from name and group if not overridden.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(help_text='Plain text representation of quote. You can use Markdown here.', max_length=280),
        ),
    ]
