# Generated by Django 4.0.2 on 2022-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_charactergroup_options_charactergroup_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='citation',
            field=models.CharField(blank=True, help_text='Where is this quote from? Episode #, book?', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='citation_url',
            field=models.URLField(blank=True, help_text='URL for citation, if applicable.', null=True),
        ),
    ]
