# Generated by Django 4.0.2 on 2022-02-12 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0003_quote_citation_quote_citation_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.BigIntegerField()),
                ('quotes_requested', models.PositiveIntegerField(default=0, help_text='Number of time child quotes have been requested.')),
                ('quotes_generated', models.PositiveIntegerField(default=0, help_text='Number of times markov generated quotes have been requested.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Times used for random quotes, etc.')),
                ('quote', models.OneToOneField(help_text='The Quote the stats related to.', on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
