# Generated by Django 4.0.2 on 2022-02-12 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoteusagestats_quotestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quotes_requested', models.PositiveIntegerField(default=0, help_text='Number of time child quotes have been requested.')),
                ('quotes_generated', models.PositiveIntegerField(default=0, help_text='Number of times markov generated quotes have been requested.')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quotes.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quotes_requested', models.PositiveIntegerField(default=0, help_text='Number of time child quotes have been requested.')),
                ('quotes_generated', models.PositiveIntegerField(default=0, help_text='Number of times markov generated quotes have been requested.')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quotes.charactergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuoteUsageStats',
        ),
    ]
