# Generated by Django 4.0.2 on 2022-02-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_characterstats_groupstats_delete_quoteusagestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotestats',
            name='quote',
            field=models.OneToOneField(help_text='The Quote the stats related to.', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quotes.quote'),
        ),
    ]
