# Generated by Django 4.0.2 on 2022-02-17 19:42

from django.db import IntegrityError
from django.db import migrations


def create_missing_group_model_objects(apps, schema_editor):
    """
    Go through and add any missing group markov models.
    """
    CharacterGroup = apps.get_model("quotes", "CharacterGroup")
    GroupMarkovModel = apps.get_model("quotes", "GroupMarkovModel")
    for group in CharacterGroup.objects.all():
        try:
            GroupMarkovModel.objects.create(group=group)
        except IntegrityError:
            pass


def remove_group_markov_model_objects(apps, schema_editor):
    """
    Remove created group markov models.
    """
    GroupMarkovModel = apps.get_model("quotes", "GroupMarkovModel")
    for gmm in GroupMarkovModel.objects.all():
        gmm.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_groupmarkovmodel"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_group_model_objects, remove_group_markov_model_objects
        )
    ]
